ssh seavvnetapp01 snapmirror resume -destination-path seav3file01:ITS_VV_ServInfBuild_W3mirror
ssh seavvnetapp01 snapmirror resume -destination-path seav3file01:ITS_VV_W3DEPLOY_W3mirror
ssh seavvnetapp01 snapmirror resume -destination-path seav3pilotbrief:pilotbriefingfs
ssh seavvnetapp01 snapmirror resume -destination-path seavvcmsfs01:CMS_Share
ssh seavvnetapp01 snapmirror resume -destination-path seavvfltopsapp:FOGSfs
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan02:seavvwmq04_jctep
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan01:seavvwmq03_jctep
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan02:seavvwmq04_qmadqx
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan01:seavvwmq03_qmadqx
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan02:seavvwmq04_qmas
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan01:seavvwmq03_qmas
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan02:seavvwmq04_qmasbsm1
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan01:seavvwmq03_qmasbsm1
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan02:seavvwmq04_qmmfp
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan01:seavvwmq03_qmmfp
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan02:seavvwmq04_s4aprod
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan01:seavvwmq03_s4aprod
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan01:seavvwmq2a
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan02:seavvwmq04_qmb2bp
ssh seavvnetapp01 snapmirror resume -destination-path seavvsan01:seavvwmq03_qmb2bp
ssh seavvnetapp01 snapmirror resume -destination-path seavvsftpfs01:ftphome
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seav3file01/seav3file01_root_mirror
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seav3file01/seav3file01_root_mirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seav3pilotbrief/seav3pilotbrief_root_05
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seav3pilotbrief/seav3pilotbrief_root_06
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvarchive1/seavvarchive1_root_mirror
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvarchive1/seavvarchive1_root_mirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvbifile01/seavvbifile01new_rootmirror1
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvbifile01/seavvbifile01new_rootmirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvcmsfs01/seavvcmsfs01_rootmirror
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvcmsfs01/seavvcmsfs01_rootmirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvdbafs01/seavvdbafs01_root_mirror
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvdbafs01/seavvdbafs01_root_mirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvfile01/seavvfile01_root_mirror
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvfile01/seavvfile01_root_mirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvfile1qx/seavvfile1qxnew_rootmirror1
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvfile1qx/seavvfile1qxnew_rootmirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvfltopsapp/seavvfltopsapp_root_mirror1
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvfltopsapp/seavvfltopsapp_root_mirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvgropsfile1/seavvgropsfile1new_rootmirror1
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvgropsfile1/seavvgropsfile1new_rootmirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvmaintfs1/seavvmaintfs1_root_mirror
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvmaintfs1/seavvmaintfs1_root_mirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvnfs01/seavvnfs01_root_mirror
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvnfs01/seavvnfs01_root_mirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvnfscifs01/seavvnfscifs01_rootmirror
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvnfscifs01/seavvnfscifs01_root_mirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvpilotbrief/seavvpilotbrief_root_05
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvpilotbrief/seavvpilotbrief_root_06
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvpsfin01/seavvpsfin01_rootmirror
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvpsfin01/seavvpsfin01_rootmirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvqcfile01/seavvqcfile01_rootmirror
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvqcfile01/seavvqcfile01_root_mirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvseclog01/seavvseclog01new_rootmirror1
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvseclog01/seavvseclog01new_rootmirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvsftpfs01/seavvsftpfs01_root_mirror1
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvsftpfs01/seavvsftpfs01_root_mirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvuhd1/seavvuhd1new_rootmirror2
ssh seavvnetapp01 snapmirror resume -destination-path seavvnetapp01://seavvuhd1/seavvuhd1new_rootmirror1
ssh seavvnetapp01 snapmirror resume -destination-path 
